import QueryProvider from "@/providers/Provider";

import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryProvider>
      <main className="px-4 mt-10 2xl:px-0 max-w-[1640px] mx-auto">
        {children}
      </main>
    </QueryProvider>
  );
}
